from __future__ import annotations


ITEM_ALIASES: dict[str, set[str]] = {
    "albedo": {"阿贝多", "Albedo"},
    "alhaitham": {"艾尔海森", "Alhaitham"},
    "arataki_itto": {"荒泷一斗", "Arataki Itto", "Itto"},
    "arlecchino": {"阿蕾奇诺", "Arlecchino"},
    "baizhu": {"白术", "Baizhu"},
    "chasca": {"恰斯卡", "Chasca"},
    "chiori": {"千织", "Chiori"},
    "citlali": {"茜特菈莉", "Citlali"},
    "clorinde": {"克洛琳德", "Clorinde"},
    "columbina": {"哥伦比娅", "Columbina"},
    "cyno": {"赛诺", "Cyno"},
    "dehya": {"迪希雅", "Dehya"},
    "durin": {"杜林", "Durin"},
    "emilie": {"艾梅莉埃", "Emilie"},
    "escoffier": {"爱可菲", "Escoffier"},
    "eula": {"优菈", "Eula"},
    "flins": {"菲林斯", "Flins"},
    "furina": {"芙宁娜", "Furina"},
    "ganyu": {"甘雨", "Ganyu"},
    "hu_tao": {"胡桃", "Hu Tao"},
    "ineffa": {"伊涅芙", "Ineffa"},
    "kaedehara_kazuha": {"枫原万叶", "万叶", "Kaedehara Kazuha", "Kazuha"},
    "kamisato_ayaka": {"神里绫华", "绫华", "Kamisato Ayaka", "Ayaka"},
    "kamisato_ayato": {"神里绫人", "绫人", "Kamisato Ayato", "Ayato"},
    "keqing": {"刻晴", "Keqing"},
    "kinich": {"基尼奇", "Kinich"},
    "klee": {"可莉", "Klee"},
    "lauma": {"菈乌玛", "Lauma"},
    "linnea": {"琳妮娅", "Linnea"},
    "lohen": {"洛恩", "Lohen"},
    "lyney": {"林尼", "Lyney"},
    "mavuika": {"玛薇卡", "Mavuika"},
    "mona": {"莫娜", "Mona"},
    "mualani": {"玛拉妮", "Mualani"},
    "nahida": {"纳西妲", "Nahida"},
    "nefer": {"奈芙尔", "Nefer"},
    "neuvillette": {"那维莱特", "Neuvillette"},
    "nicole": {"尼可", "Nicole"},
    "nilou": {"妮露", "Nilou"},
    "raiden_shogun": {"雷电将军", "雷神", "Raiden Shogun", "Raiden"},
    "sangonomiya_kokomi": {"珊瑚宫心海", "心海", "Sangonomiya Kokomi", "Kokomi"},
    "sandrone": {"桑多涅", "Sandrone"},
    "shenhe": {"申鹤", "Shenhe"},
    "sigewinne": {"希格雯", "Sigewinne"},
    "skirk": {"丝柯克", "Skirk"},
    "tartaglia": {"达达利亚", "公子", "Tartaglia", "Childe"},
    "tighnari": {"提纳里", "Tighnari"},
    "venti": {"温迪", "Venti"},
    "wanderer": {"流浪者", "散兵", "Wanderer"},
    "wriothesley": {"莱欧斯利", "Wriothesley"},
    "xiao": {"魈", "Xiao"},
    "xilonen": {"希诺宁", "Xilonen"},
    "yae_miko": {"八重神子", "Yae Miko"},
    "yelan": {"夜兰", "Yelan"},
    "yoimiya": {"宵宫", "Yoimiya"},
    "yumemizuki_mizuki": {"梦见月瑞希", "瑞希", "Yumemizuki Mizuki", "Mizuki"},
    "zhongli": {"钟离", "Zhongli"},
    "zibai": {"兹白", "子白", "Zibai"},

    "a_thousand_blazing_suns": {"焚曜千阳", "A Thousand Blazing Suns"},
    "a_thousand_floating_dreams": {"千夜浮梦", "A Thousand Floating Dreams"},
    "absolution": {"赦罪", "Absolution"},
    "amos_bow": {"阿莫斯之弓", "Amos' Bow", "Amos Bow"},
    "aqua_simulacra": {"若水", "Aqua Simulacra"},
    "astral_vultures_crimson_plumage": {"星鹫赤羽", "Astral Vulture's Crimson Plumage"},
    "azurelight": {"苍耀", "Azurelight"},
    "beacon_of_the_reed_sea": {"苇海信标", "Beacon of the Reed Sea"},
    "calamity_queller": {"息灾", "Calamity Queller"},
    "cashflow_supervision": {"金流监督", "Cashflow Supervision"},
    "cranes_echoing_call": {"鹤鸣余音", "Crane's Echoing Call"},
    "crimson_moons_semblance": {"赤月之形", "Crimson Moon's Semblance"},
    "elegy_for_the_end": {"终末嗟叹之诗", "Elegy for the End"},
    "engulfing_lightning": {"薙草之稻光", "Engulfing Lightning"},
    "everlasting_moonglow": {"不灭月华", "Everlasting Moonglow"},
    "fang_of_the_mountain_king": {"山王长牙", "Fang of the Mountain King"},
    "freedom-sworn": {"苍古自由之誓", "Freedom-Sworn", "Freedom Sworn"},
    "fractured_halo": {"残毁的环冕", "Fractured Halo"},
    "haran_geppaku_futsu": {"波乱月白经津", "Haran Geppaku Futsu"},
    "hunters_path": {"猎人之径", "Hunter's Path"},
    "jadefalls_splendor": {"碧落之珑", "Jadefall's Splendor"},
    "kaguras_verity": {"神乐之真意", "Kagura's Verity"},
    "key_of_khaj-nisut": {"圣显之钥", "Key of Khaj-Nisut"},
    "light_of_foliar_incision": {"裁叶萃光", "Light of Foliar Incision"},
    "lost_prayer_to_the_sacred_winds": {"四风原典", "Lost Prayer to the Sacred Winds"},
    "lumidouce_elegy": {"柔灯挽歌", "Lumidouce Elegy"},
    "memory_of_dust": {"尘世之锁", "Memory of Dust"},
    "mistsplitter_reforged": {"雾切之回光", "Mistsplitter Reforged"},
    "peak_patrol_song": {"岩峰巡歌", "Peak Patrol Song"},
    "polar_star": {"冬极白星", "Polar Star"},
    "primordial_jade_cutter": {"磐岩结绿", "Primordial Jade Cutter"},
    "primordial_jade_winged-spear": {"和璞鸢", "Primordial Jade Winged-Spear"},
    "redhorn_stonethresher": {"赤角石溃杵", "Redhorn Stonethresher"},
    "skyward_atlas": {"天空之卷", "Skyward Atlas"},
    "skyward_blade": {"天空之刃", "Skyward Blade"},
    "skyward_harp": {"天空之翼", "Skyward Harp"},
    "skyward_pride": {"天空之傲", "Skyward Pride"},
    "skyward_spine": {"天空之脊", "Skyward Spine"},
    "song_of_broken_pines": {"松籁响起之时", "Song of Broken Pines"},
    "splendor_of_tranquil_waters": {"静水流涌之辉", "Splendor of Tranquil Waters"},
    "staff_of_homa": {"护摩之杖", "Staff of Homa"},
    "staff_of_the_scarlet_sands": {"赤沙之杖", "Staff of the Scarlet Sands"},
    "starcallers_watch": {"祭星者之望", "Starcaller's Watch", "Starcallers Watch"},
    "summit_shaper": {"斫峰之刃", "Summit Shaper"},
    "surfs_up": {"冲浪时光", "Surf's Up"},
    "symphonist_of_scents": {"香韵奏者", "Symphonist of Scents"},
    "the_first_great_magic": {"最初的大魔术", "The First Great Magic"},
    "thundering_pulse": {"飞雷之弦振", "Thundering Pulse"},
    "tome_of_the_eternal_flow": {"万世流涌大典", "Tome of the Eternal Flow"},
    "tulaytullahs_remembrance": {"图莱杜拉的回忆", "Tulaytullah's Remembrance"},
    "uraku_misugiri": {"有乐御簾切", "有乐御帘切", "Uraku Misugiri"},
    "verdict": {"裁断", "Verdict"},
    "vivid_notions": {"寝正月初晴", "Vivid Notions"},
    "vortex_vanquisher": {"贯虹之槊", "Vortex Vanquisher"},
    "wolfs_gravestone": {"狼的末路", "Wolf's Gravestone"},
}
